// <auto-generated />
using System;
using System.Text.Json;
using ConfigHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfigHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConfigHubDbContext))]
    [Migration("20260831120743_AddBaselineReviewWorkflow")]
    partial class AddBaselineReviewWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation_id");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_entity_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("locked_by");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_background_jobs_created_at");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_background_jobs_claim");

                    b.ToTable("background_jobs", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComponentCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("component_code_snapshot");

                    b.Property<string>("ComponentNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component_name_snapshot");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_version_id");

                    b.Property<Guid>("ConfigurationBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_baseline_id");

                    b.Property<Guid>("ConfigurationComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_component_id");

                    b.Property<string>("LineageKeySnapshot")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("lineage_key_snapshot");

                    b.Property<Guid?>("ParentBaselineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_baseline_item_id");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("requirement");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("VersionNumberSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_number_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .HasDatabaseName("ix_baseline_items_version");

                    b.HasIndex("ConfigurationComponentId");

                    b.HasIndex("ParentBaselineItemId");

                    b.HasIndex("ConfigurationBaselineId", "ConfigurationComponentId")
                        .IsUnique()
                        .HasDatabaseName("ux_baseline_items_baseline_component");

                    b.HasIndex("ConfigurationBaselineId", "ParentBaselineItemId", "SortOrder")
                        .HasDatabaseName("ix_baseline_items_baseline_parent_sort");

                    b.ToTable("baseline_items", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineLifecycleTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor");

                    b.Property<Guid>("ConfigurationBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_baseline_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationBaselineId", "OccurredAt")
                        .HasDatabaseName("ix_baseline_lifecycle_transitions_baseline_occurred_at");

                    b.ToTable("baseline_lifecycle_transitions", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfigurationBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_baseline_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("RequestReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("request_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationBaselineId")
                        .IsUnique()
                        .HasDatabaseName("ux_baseline_reviews_pending_baseline")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("ConfigurationBaselineId", "RequestedAt")
                        .HasDatabaseName("ix_baseline_reviews_baseline_requested_at");

                    b.ToTable("baseline_reviews", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedSeriesCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_series_code");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("series_code");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "NormalizedSeriesCode")
                        .IsUnique()
                        .HasDatabaseName("ux_baseline_series_project_code");

                    b.ToTable("baseline_series", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Maturity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("maturity");

                    b.Property<string>("NormalizedVersionNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_version_number");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("safety");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "NormalizedVersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_component_versions_normalized_number");

                    b.HasIndex("ComponentId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_component_versions_sequence_no");

                    b.ToTable("component_versions", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("approved_by");

                    b.Property<string>("BaselineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("baseline_code");

                    b.Property<Guid>("BaselineSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("baseline_series_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("NormalizedBaselineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_baseline_code");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("released_by");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("revision_no");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid?>("SupersedesBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_baseline_id");

                    b.Property<Guid?>("TopComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("top_component_version_id");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesBaselineId");

                    b.HasIndex("TopComponentVersionId")
                        .HasDatabaseName("ix_configuration_baselines_top_version");

                    b.HasIndex("BaselineSeriesId", "RevisionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_baselines_series_revision");

                    b.HasIndex("ProjectId", "NormalizedBaselineCode")
                        .IsUnique()
                        .HasDatabaseName("ux_configuration_baselines_project_code");

                    b.ToTable("configuration_baselines", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("component_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LineageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("lineage_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedComponentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_component_code");

                    b.Property<Guid?>("ParentComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_component_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ParentComponentId");

                    b.HasIndex("ProjectId", "LineageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_components_project_lineage");

                    b.HasIndex("ProjectId", "NormalizedComponentCode")
                        .IsUnique()
                        .HasDatabaseName("ux_components_project_code");

                    b.HasIndex("ProjectId", "ParentComponentId", "SortOrder")
                        .HasDatabaseName("ix_components_project_parent_sort");

                    b.ToTable("configuration_components", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.DeploymentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_type");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "EffectiveAt")
                        .HasDatabaseName("ix_deployment_batches_machine_effective_at");

                    b.HasIndex("SourceType", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_deployment_batches_source_event")
                        .HasFilter("external_event_id IS NOT NULL");

                    b.ToTable("deployment_batches", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.DeploymentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfigurationComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_component_id");

                    b.Property<Guid>("DeploymentBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_batch_id");

                    b.Property<DateTimeOffset?>("KnownInstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_installed_at");

                    b.Property<Guid?>("NewComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_component_version_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationComponentId");

                    b.HasIndex("DeploymentBatchId", "ConfigurationComponentId")
                        .IsUnique()
                        .HasDatabaseName("ux_deployment_items_batch_component");

                    b.HasIndex("NewComponentVersionId", "Result")
                        .HasDatabaseName("ix_deployment_items_version_result");

                    b.ToTable("deployment_items", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<JsonDocument>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Scope", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_scope_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_import_batches_project_created_at");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("ValidationError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("validation_error");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_import_rows_batch_row");

                    b.ToTable("import_rows", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MachineType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("machine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedSerialNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_serial_number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_machines_normalized_serial");

                    b.HasIndex("ProjectId", "Status", "MachineType")
                        .HasDatabaseName("ix_machines_project_status_type");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineCurrentConfiguration", b =>
                {
                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<Guid>("ConfigurationComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_component_id");

                    b.Property<Guid?>("ComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_version_id");

                    b.Property<DateTimeOffset?>("KnownInstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_installed_at");

                    b.Property<Guid>("SourceDeploymentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_deployment_item_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateEffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_effective_at");

                    b.HasKey("MachineId", "ConfigurationComponentId");

                    b.HasIndex("ConfigurationComponentId");

                    b.HasIndex("SourceDeploymentItemId");

                    b.HasIndex("ComponentVersionId", "MachineId")
                        .HasDatabaseName("ix_machine_current_configurations_version_machine");

                    b.ToTable("machine_current_configurations", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineDriftSummary", b =>
                {
                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("match_status");

                    b.Property<string>("RiskSeverity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("risk_severity");

                    b.HasKey("MachineId");

                    b.ToTable("machine_drift_summaries", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineTargetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ConfigurationBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_baseline_id");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationBaselineId");

                    b.HasIndex("MachineId")
                        .IsUnique()
                        .HasDatabaseName("ux_machine_target_assignments_current_machine")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("machine_target_assignments", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_normalized_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ProjectMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_memberships_user");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_memberships_project_user");

                    b.ToTable("project_memberships", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ProjectStandardAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ConfigurationBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuration_baseline_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationBaselineId");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_standard_assignments_current_project")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("project_standard_assignments", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.VersionLifecycleTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("axis");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_version_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId", "OccurredAt")
                        .HasDatabaseName("ix_version_lifecycle_transitions_version_occurred_at");

                    b.ToTable("version_lifecycle_transitions", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.VersionRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_version_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("revoked_by");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId")
                        .IsUnique()
                        .HasDatabaseName("ux_version_recommendations_active_component")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("ComponentVersionId");

                    b.ToTable("version_recommendations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineItem", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.BaselineItem", null)
                        .WithMany()
                        .HasForeignKey("ParentBaselineItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineLifecycleTransition", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineReview", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.BaselineSeries", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.BaselineSeries", null)
                        .WithMany()
                        .HasForeignKey("BaselineSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("SupersedesBaselineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("TopComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.DeploymentBatch", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.DeploymentItem", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.DeploymentBatch", null)
                        .WithMany()
                        .HasForeignKey("DeploymentBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("NewComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ImportBatch", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ImportRow", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.Machine", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineCurrentConfiguration", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.DeploymentItem", null)
                        .WithMany()
                        .HasForeignKey("SourceDeploymentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineDriftSummary", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.MachineTargetAssignment", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ProjectMembership", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.ProjectStandardAssignment", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationBaseline", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.VersionLifecycleTransition", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigHub.Infrastructure.Persistence.Entities.VersionRecommendation", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ConfigurationComponent", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ComponentVersion", null)
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ConfigHub.Infrastructure.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
